---
- name: Stat starship command
  stat:
    path: /usr/local/bin/starship
  register: starship_command
- name: Install starship command
  when: starship_command.stat.executable is not defined
  block:
    - name: Unarchive starship command for Linux
      when: ansible_system == "Linux" and ansible_architecture == "x86_64"
      unarchive:
        src: "https://github.com/starship/starship/releases/download/{{ starship.version }}/starship-x86_64-unknown-linux-musl.tar.gz"
        dest: /usr/local/bin
        remote_src: true
    - name: Unarchive starship command for macOS
      when: ansible_distribution == "MacOSX"
      unarchive:
        src: "https://github.com/starship/starship/releases/download/{{ starship.version }}/starship-x86_64-apple-darwin.tar.gz"
        dest: /usr/local/bin
        remote_src: true
